---
- name: Install nginx on servers
  hosts: pvt
  gather_facts: yes
  become: yes
  become_user: root
  tags: nginx
  vars:
   [version: 1.0.0, port: 80, state: present]
  tasks:
  - name: perform apt update 
    shell: apt-get update
  - name: Install Nginx
    shell: apt-get install -y nginx 
  - name: start Nginx server
    shell: service nginx start && systemctl enable nginx 


- name: Installing base tools
  hosts: pvt
  gather_facts: yes
  become: yes
  become_user: root
  tags: basetools
  tasks:
  - name: Install base tools
    apt: name={{ item }}  state=present
    with_items:
     - unzip
     - certbot
     - net-tools
     - jq    